# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da41947d13eb7a65281e05a6990e2045e542ddbcb864cad34d293f825cd2c7c4fdc2517a04318e81c5cdbeffca131099b82f4d8ac2b80e1cbc26e8ea75c8b6ff

test:
  secret_key_base: 843bb1d0dba853b145a3259da0d58ddebfa97b35d6fd3203728de3834e03aeba656fba55d754d47ace391dec89c5c693d5de7346f76e2062bfe392347ea58906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
